### ISSUE TITLE
TODO: config option to be able disabling db memory journaling/caching

### ISSUE THREAD

**Issue by yarikoptic** [fail2ban/fail2ban#1437]
as discussed  https://github.com/fail2ban/fail2ban/pull/1436#discussion_r64035254

**Comment by sebres** [comment]
**speedup (0.9, 0.10)**
- [ ] - new section for database options `Database`
```
[Database]

# the same as Definition.dbfile:
file = ...
# the same as Definition.dbpurgeage:
purgeage ...

# write data through OS without syncing:
synchronous = off
# use memory for the transaction logging:
journal_mode = memory
# temporary tables and indices are kept in memory:
temp_store = memory
```

**caching, other 0.10 options**
- [ ] - options `iptoname_cache`, `nametoip_cache` for dns caching (fail2ban.conf):
```
# caching parameters (expiration time, max size of cache), leave empty to disable cache:
nametoip_cache=1m,1000
iptoname_cache=1m,1000
```
- [ ] - option `inertance` for specifying of default sleep time and interval in polling algorithms, by using of `wait_for` (fail2ban.conf):
```
# inertance - specify sleep time, threshold interval for default wait operation (in polling algorithms),
# small values allow to react fail2ban faster (but causes higher cpu/disc load), larger values - vice versa
inertance = 2,0.25
```
- [ ] - option `maxfailures` max number of the last matches/failures, fail2ban will hold per IP in the list of failures in failmanager resp. in the database (jail.conf);
```
# maxfailures - max number of the last matches/failures, fail2ban will hold per IP in the list of failures 
# in memory resp. in the database (to send it by ban via e-mail, etc.)
maxfailures = 10
```
- [ ] - option `garbage` (fail2ban.conf):
```
# specify time, threshold to execute garbage collector in background service of fail2ban,
# leave empty for default python garbage collector behavior
# garbage=30s,100
garbage =
```
- [ ] - ChangeLog entries;

**Comment by yarikoptic** [comment]
So @sebres should we wait for 'db-speedup' to happen or release without?

**Comment by sebres** [comment]
You are the boss... I'm on vacation 2 weeks from next one, and probably I won't get out until my vacation. But we will see...

**Comment by sebres** [comment]
new db option `auto_recover = ?file? ?type?`, see #1465
