### ISSUE TITLE
(0.10.4) missed matches with Postfix log AUTH/CONNECT (possibly also SASL error) misses

### ISSUE THREAD

**Issue by ChristopherW** [fail2ban/fail2ban#2624]
_Hi devs! Long time listener, first time caller, love your work..._

### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.10.4
- OS, including release name/version: CentOS Linux release 7.7.1908 (Core), Python 2.7.5
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration

### The issue:

fail2ban 0.10.4 on CentOS 7 seems unable to match lines from `/var/log/maillog` logged by Postfix as a result of clients connecting and failing EHLO, CONNECT etc. I've tried a few permutations of a regex, getting increasingly generous with my matching each time, and also adding lines via postfix.local, but they always miss. Testing with fail2ban-regex.

#### Steps to reproduce
Run Postfix logging as usual, logging to `/var/log/maillog`. Excerpt at end of this post.

#### Expected behavior

I'd expect f2b to match these various connection/disconnection and block the EHLO and lost connection after CONNECT entries.

#### Observed behavior
None of the bruteforce connection lost messages are caught; the Postfix filter only matches NOQUEUE bounce lines.

Running the command `fail2ban-regex /var/log/maillog /etc/fail2ban/filter.d/postfix.local --print-all-matched`:

```
Running tests
=============

Use   failregex filter file : postfix, basedir: /etc/fail2ban
Use      datepattern : Default Detectors
Use         log file : /var/log/maillog
Use         encoding : UTF-8


Results
=======

Failregex: 78 total
|-  #) [# of hits] regular expression
|   1) [78] ^RCPT from [^[]*\[<HOST>\](?::\d+)?: 55[04] 5\.7\.1\s
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [49033] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
`-

Lines: 49033 lines, 0 ignored, 78 matched, 48955 missed
[processed in 4.39 sec]

|- Matched line(s):
|  Feb  2 07:42:56 l03 postfix/smtpd[4461]: NOQUEUE: reject: RCPT from s194089.cloud.flynet.pro[193.47.34.3]: 554 5.7.1 Service unavailable; Client host [193.47.34.3] blocked using sbl.spamhaus.org; https://www.spamhaus.org/sbl/query/SBLCSS; from=<812956218314@cwu.edu> to=<mboconnect2019@hotmail.com> proto=ESMTP helo=<cwu.edu>
|  Feb  2 11:31:23 l03 postfix/smtpd[31987]: NOQUEUE: reject: RCPT from host217-43-8-215.range217-43.btcentralplus.com[217.43.8.215]: 554 5.7.1 Service unavailable; Client host [217.43.8.215] blocked using sbl.spamhaus.org; https://www.spamhaus.org/sbl/query/SBLCSS; from=<info@investworld.pw> to=<sales@example.com> proto=ESMTP helo=<host86-140-80-205.range86-140.btcentralplus.com>
|  Feb  2 11:53:31 l03 postfix/smtpd[20620]: NOQUEUE: reject: RCPT from unknown[63.83.73.152]: 554 5.7.1 Service unavailable; Client host [63.83.73.152] blocked using sbl.spamhaus.org; https://www.spamhaus.org/sbl/query/SBLCSS; from=<Inexperiencedshooters@boostpowers.us> to=<enquiries@example.com> proto=ESMTP helo=<06b8a750.boostpowers.us>

(...etc)
```

#### Any additional information
This particular server was deployed via Webmin's autoinstaller script, and f2b is installed from yum repo as part of this; I deployed the OS.

### Configuration, dump and another helpful excerpts

Postfix.conf is default; postfix.local only adds 

```
[Definition]
failregex = %(known/failregex)s
            lost connection after (AUTH|UNKNOWN|EHLO) from [^[]*\[<HOST>\](?::\d+)?
```

`postfix.conf` contents:
```
# Fail2Ban filter for selected Postfix SMTP rejections
#
#

[INCLUDES]

# Read common prefixes. If any customizations available -- read them from
# common.local
before = common.conf

[Definition]

_daemon = postfix(-\w+)?/\w+(?:/smtp[ds])?
_port = (?::\d+)?

prefregex = ^%(__prefix_line)s<mdpr-<mode>> <F-CONTENT>.+</F-CONTENT>$

mdpr-normal = (?:NOQUEUE: reject:|improper command pipelining after \S+)
mdre-normal=^RCPT from [^[]*\[<HOST>\]%(_port)s: 55[04] 5\.7\.1\s
            ^RCPT from [^[]*\[<HOST>\]%(_port)s: 45[04] 4\.7\.1 (?:Service unavailable\b|Client host rejected: cannot find your (reverse )?hostname\b)
            ^RCPT from [^[]*\[<HOST>\]%(_port)s: 450 4\.7\.1 (<[^>]*>)?: Helo command rejected: Host not found\b
            ^EHLO from [^[]*\[<HOST>\]%(_port)s: 504 5\.5\.2 (<[^>]*>)?: Helo command rejected: need fully-qualified hostname\b
            ^VRFY from [^[]*\[<HOST>\]%(_port)s: 550 5\.1\.1\s
            ^RCPT from [^[]*\[<HOST>\]%(_port)s: 450 4\.1\.8 (<[^>]*>)?: Sender address rejected: Domain not found\b
            ^from [^[]*\[<HOST>\]%(_port)s:?

mdpr-auth = warning:
mdre-auth = ^[^[]*\[<HOST>\]%(_port)s: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed:(?! Connection lost to authentication server| Invalid authentication mechanism)
mdre-auth2= ^[^[]*\[<HOST>\]%(_port)s: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed:(?! Connection lost to authentication server)
# todo: check/remove "Invalid authentication mechanism" from ignore list, if gh-1243 will get finished (see gh-1297).

# Mode "rbl" currently included in mode "normal", but if needed for jail "postfix-rbl" only:
mdpr-rbl = %(mdpr-normal)s
mdre-rbl  = ^RCPT from [^[]*\[<HOST>\]%(_port)s: [45]54 [45]\.7\.1 Service unavailable; Client host \[\S+\] blocked\b

# Mode "rbl" currently included in mode "normal" (within 1st rule)
mdpr-more = %(mdpr-normal)s
mdre-more = %(mdre-normal)s

mdpr-ddos = lost connection after(?! DATA) [A-Z]+
mdre-ddos = ^from [^[]*\[<HOST>\]%(_port)s:?

mdpr-extra = (?:%(mdpr-auth)s|%(mdpr-normal)s)
mdre-extra = %(mdre-auth)s
            %(mdre-normal)s

mdpr-aggressive = (?:%(mdpr-auth)s|%(mdpr-normal)s|%(mdpr-ddos)s)
mdre-aggressive = %(mdre-auth2)s
                  %(mdre-normal)s



failregex = <mdre-<mode>>

# Parameter "mode": more (default combines normal and rbl), auth, normal, rbl, ddos, extra or aggressive (combines all)
# Usage example (for jail.local):
#   [postfix]
#   mode = aggressive
#   # or another jail (rewrite filter parameters of jail):
#   [postfix-rbl]
#   filter = postfix[mode=rbl]
#
mode = more

ignoreregex =

[Init]

journalmatch = _SYSTEMD_UNIT=postfix.service

# Author: Cyril Jaquier
```

With fail2ban-regex, I've also tried things like `^lost connection after (AUTH|UNKNOWN|EHLO) from [^\[]*\[<HOST>\]\s$`, `lost connection after (AUTH|UNKNOWN|EHLO) from <HOST>\s` and all manner of simpler permutations which should have instantly matched. I've tried against the log file and also against a line in single quotes at the prompt.

#### Any customizations done to /etc/fail2ban/ configuration

`jail.conf` has `before = paths-fedora.conf`, `destemail` and `sender` defined; 

`jail.local` includes a few ignoreip entres, and a few more jails enabled, including

```
[postfix]

enabled  = true
port     = smtp,465,submission

[dovecot]

enabled = true
port    = pop3,pop3s,imap,imaps,submission,465,sieve

[postfix-sasl]

enabled  = true
port     = smtp,465,submission,imap3,imaps,pop3,pop3s
maxretry = 5

[postfix-auth]
enabled     = true
filter      = postfix-auth
action      = iptables-multiport[name=postfix, port="http,https,smtp,submission,pop3,pop3s,imap,imaps,sieve", protocol=tcp]
#           sendmail[name=Postfix, dest=you@mail.com]
logpath     = /var/log/maillog
maxretry = 5
```

#### Relevant parts of /var/log/fail2ban.log file:
```
2020-02-06 14:16:52,369 fail2ban.filtersystemd  [23139]: HEAVY   [postfix] Read systemd journal entry: 2020-02-06T14:16:52.362258 l03.example.com postfix/smtpd[15601]: lost connection after CONNECT from unknown[125.123.71.177]
2020-02-06 14:16:52,370 fail2ban.filter         [23139]: HEAVY   Looking for match of [('', '2020-02-06T14:16:52.362258', 'l03.example.com postfix/smtpd[15601]: lost connection after CONNECT from unknown[125.123.71.177]')]
2020-02-06 14:16:52,369 fail2ban.filter         [23139]: HEAVY     Looking for failregex 1 - '^(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel: \\[ *\\d+\\.\\d+\\]\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?webmin(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?webmin(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?Invalid login as .+ from (?:(?:::f{4,6}:)?(?P<ip4>(?:\\d{1,3}\\.){3}\\d{1,3})|\\[?(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):))\\]?|(?P<dns>[\\w\\-.^_]*\\w))\\s*$'
2020-02-06 14:16:52,370 fail2ban.filter         [23139]: HEAVY     Looking for prefregex '^(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel: \\[ *\\d+\\.\\d+\\]\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?postfix(-\\w+)?/\\w+(?:/smtp[ds])?(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?postfix(-\\w+)?/\\w+(?:/smtp[ds])?(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?(?:NOQUEUE: reject:|improper command pipelining after \\S+) (?P<content>.+)$'
2020-02-06 14:16:52,371 fail2ban.filter         [23139]: HEAVY     Prefregex not matched
```

```
2020-02-06 14:16:52,369 fail2ban.filtersystemd  [23139]: HEAVY   [postfix] Read systemd journal entry: 2020-02-06T14:16:52.362258 l03.example.com postfix/smtpd[15601]: lost connection after CONNECT from unknown[125.123.71.177]
2020-02-06 14:16:52,370 fail2ban.filter         [23139]: HEAVY   Looking for match of [('', '2020-02-06T14:16:52.362258', 'l03.example.com postfix/smtpd[15601]: lost connection after CONNECT from unknown[125.123.71.177]')]
2020-02-06 14:16:52,369 fail2ban.filter         [23139]: HEAVY     Looking for failregex 1 - '^(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel: \\[ *\\d+\\.\\d+\\]\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?webmin(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?webmin(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?Invalid login as .+ from (?:(?:::f{4,6}:)?(?P<ip4>(?:\\d{1,3}\\.){3}\\d{1,3})|\\[?(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):))\\]?|(?P<dns>[\\w\\-.^_]*\\w))\\s*$'
2020-02-06 14:16:52,370 fail2ban.filter         [23139]: HEAVY     Looking for prefregex '^(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel: \\[ *\\d+\\.\\d+\\]\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?postfix(-\\w+)?/\\w+(?:/smtp[ds])?(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?postfix(-\\w+)?/\\w+(?:/smtp[ds])?(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?(?:NOQUEUE: reject:|improper command pipelining after \\S+) (?P<content>.+)$'
2020-02-06 14:16:52,371 fail2ban.filter         [23139]: HEAVY     Prefregex not matched
```

```
2020-02-06 14:16:52,384 fail2ban.filtersystemd  [23139]: HEAVY   [postfix-sasl] Read systemd journal entry: 2020-02-06T14:16:52.363677 l03.example.com postfix/smtpd[15601]: disconnect from unknown[125.123.71.177]
2020-02-06 14:16:52,372 fail2ban.filtersystemd  [23139]: HEAVY   [postfix] Read systemd journal entry: 2020-02-06T14:16:52.363677 l03.example.com postfix/smtpd[15601]: disconnect from unknown[125.123.71.177]
2020-02-06 14:16:52,385 fail2ban.filter         [23139]: HEAVY   Looking for match of [('', '2020-02-06T14:16:52.363677', 'l03.example.com postfix/smtpd[15601]: disconnect from unknown[125.123.71.177]')]
2020-02-06 14:16:52,385 fail2ban.filter         [23139]: HEAVY   Looking for match of [('', '2020-02-06T14:16:52.363677', 'l03.example.com postfix/smtpd[15601]: disconnect from unknown[125.123.71.177]')]
2020-02-06 14:16:52,385 fail2ban.filter         [23139]: HEAVY     Looking for prefregex '^(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel: \\[ *\\d+\\.\\d+\\]\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?postfix(-\\w+)?/\\w+(?:/smtp[ds])?(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?postfix(-\\w+)?/\\w+(?:/smtp[ds])?(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?warning: (?P<content>.+)$'
2020-02-06 14:16:52,385 fail2ban.filter         [23139]: HEAVY     Looking for prefregex '^(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel: \\[ *\\d+\\.\\d+\\]\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?postfix(-\\w+)?/\\w+(?:/smtp[ds])?(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?postfix(-\\w+)?/\\w+(?:/smtp[ds])?(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?(?:NOQUEUE: reject:|improper command pipelining after \\S+) (?P<content>.+)$'
2020-02-06 14:16:52,385 fail2ban.filter         [23139]: HEAVY     Prefregex not matched
2020-02-06 14:16:52,386 fail2ban.filter         [23139]: HEAVY     Prefregex not matched
```

#### Relevant lines from monitored log files in question:

Example log output of bot/unwanted connection attempts, in amongst a couple of one-off aborted connections (e.g. the mailhostbox MTA, which I know specifically was a remote server failure as that usually delivers legitimate mail OK):

```
Feb  6 08:50:13 l03 postfix/smtpd[32323]: lost connection after EHLO from unknown[125.123.65.108]
Feb  6 08:50:21 l03 postfix/smtpd[1596]: lost connection after EHLO from unknown[125.123.65.108]
Feb  6 08:50:24 l03 postfix/smtpd[32323]: lost connection after EHLO from unknown[125.123.65.108]
Feb  6 08:50:26 l03 postfix/smtpd[1596]: lost connection after EHLO from unknown[125.123.65.108]
Feb  6 08:50:27 l03 postfix/smtpd[32323]: lost connection after EHLO from unknown[125.123.65.108]
Feb  6 08:50:28 l03 postfix/smtpd[1596]: lost connection after EHLO from unknown[125.123.65.108]
Feb  6 08:50:30 l03 postfix/smtpd[32323]: lost connection after EHLO from unknown[125.123.65.108]
Feb  6 08:50:31 l03 postfix/smtpd[1596]: lost connection after EHLO from unknown[125.123.65.108]
Feb  6 09:03:09 l03 postfix/smtpd[19246]: lost connection after UNKNOWN from ns3156300.ip-51-91-212.eu[51.91.212.80]
Feb  6 09:08:32 l03 postfix/smtpd[25068]: lost connection after EHLO from unknown[183.230.82.6]
Feb  6 09:21:38 l03 postfix/smtpd[24030]: lost connection after EHLO from unknown[78.128.113.89]
Feb  6 09:27:00 l03 postfix/smtps/smtpd[14429]: lost connection after CONNECT from unknown[123.21.189.139]
Feb  6 09:27:00 l03 postfix/smtps/smtpd[14432]: lost connection after CONNECT from unknown[123.21.135.117]
Feb  6 09:27:00 l03 postfix/smtps/smtpd[14434]: lost connection after CONNECT from unknown[123.20.26.72]
Feb  6 09:27:00 l03 postfix/smtps/smtpd[14431]: lost connection after CONNECT from unknown[123.20.50.239]
Feb  6 09:27:01 l03 postfix/smtps/smtpd[14429]: lost connection after CONNECT from unknown[123.21.20.105]
Feb  6 09:27:02 l03 postfix/smtps/smtpd[14434]: lost connection after CONNECT from unknown[117.5.44.237]
Feb  6 09:32:03 l03 postfix/smtps/smtpd[14432]: lost connection after CONNECT from unknown[123.21.21.173]
Feb  6 09:32:05 l03 postfix/smtps/smtpd[14434]: lost connection after CONNECT from unknown[14.169.101.181]
Feb  6 09:46:08 l03 postfix/smtpd[2886]: lost connection after STARTTLS from us2-ob3-7.mailhostbox.com[208.91.199.220]
Feb  6 09:46:57 l03 postfix/smtpd[2886]: lost connection after EHLO from unknown[80.66.81.86]
Feb  6 09:51:54 l03 postfix/smtpd[2886]: lost connection after EHLO from unknown[125.123.70.47]
Feb  6 09:51:55 l03 postfix/smtpd[2886]: lost connection after EHLO from unknown[125.123.70.47]
Feb  6 09:51:56 l03 postfix/smtpd[2886]: lost connection after EHLO from unknown[125.123.70.47]
Feb  6 09:52:43 l03 postfix/smtpd[2886]: lost connection after EHLO from unknown[125.123.70.47]
Feb  6 09:52:44 l03 postfix/smtpd[2886]: lost connection after EHLO from unknown[125.123.70.47]
Feb  6 09:52:46 l03 postfix/smtpd[2886]: lost connection after EHLO from unknown[125.123.70.47]
Feb  6 09:52:48 l03 postfix/smtpd[2886]: lost connection after EHLO from unknown[125.123.70.47]
Feb  6 09:52:59 l03 postfix/smtpd[2886]: lost connection after CONNECT from unknown[125.123.70.47]
Feb  6 09:53:00 l03 postfix/smtpd[2886]: lost connection after EHLO from unknown[125.123.70.47]
Feb  6 09:53:03 l03 postfix/smtpd[2886]: lost connection after EHLO from unknown[125.123.70.47]
Feb  6 09:53:05 l03 postfix/smtpd[2886]: lost connection after EHLO from unknown[125.123.70.47]
Feb  6 09:53:06 l03 postfix/smtpd[2886]: lost connection after EHLO from unknown[125.123.70.47]
Feb  6 09:53:11 l03 postfix/smtpd[2886]: lost connection after EHLO from unknown[125.123.70.47]
Feb  6 09:53:15 l03 postfix/smtpd[2886]: lost connection after EHLO from unknown[125.123.70.47]
Feb  6 09:53:17 l03 postfix/smtpd[2886]: lost connection after EHLO from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
Feb  6 09:53:19 l03 postfix/smtpd[2886]: lost connection after EHLO from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
Feb  6 09:53:21 l03 postfix/smtpd[11727]: lost connection after EHLO from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
Feb  6 09:53:23 l03 postfix/smtpd[2886]: lost connection after EHLO from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
Feb  6 09:53:26 l03 postfix/smtpd[11727]: lost connection after EHLO from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
Feb  6 09:53:28 l03 postfix/smtpd[2886]: lost connection after EHLO from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
Feb  6 12:57:22 l03 postfix/smtpd[24476]: lost connection after EHLO from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
Feb  6 12:57:22 l03 postfix/smtpd[24476]: disconnect from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
Feb  6 12:57:23 l03 postfix/smtpd[26292]: lost connection after EHLO from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
Feb  6 12:57:23 l03 postfix/smtpd[26292]: disconnect from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
Feb  6 12:57:23 l03 postfix/smtpd[29554]: lost connection after EHLO from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
Feb  6 12:57:23 l03 postfix/smtpd[29554]: disconnect from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
Feb  6 12:57:23 l03 postfix/smtpd[27914]: connect from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
Feb  6 12:57:23 l03 postfix/smtpd[26292]: connect from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
Feb  6 12:57:23 l03 postfix/smtpd[27914]: lost connection after EHLO from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
Feb  6 12:57:23 l03 postfix/smtpd[27914]: disconnect from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
Feb  6 12:57:24 l03 postfix/smtpd[24476]: connect from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
```

**Comment by sebres** [comment]
> I've tried a few permutations of a regex, getting increasingly generous with my matching each time, and also adding lines via postfix.local, but they always miss. Testing with fail2ban-regex.

Shortly you're trying to extend existing filter that has some (dynamical) features, for example `prefregex` which is depending on `mode` parameter.
So if you're not use some mode in jail, your enhancements (affecting `failregex` only) doing nothing, because `prefregex` (corresponding selected mode) simply does not match.

BTW, what you are trying is already implemented in our stock filter (at least in current version 0.10.5, but perhaps already in 0.10.4), using modes `ddos` (DDoS only) and `aggressive` (single jail for all modes together).

As for trying via `fail2ban-regex` with your excerpt (using mode `aggressive`):
<details><summary>PoC (example of fail2ban-regex ... 'postfix[mode=aggressive]') ...</summary>

```
$ fail2ban-regex /tmp/gh-2624.txt 'postfix[mode=aggressive]'

Running tests
=============

Use   failregex filter file : postfix, basedir: /etc/fail2ban/
Use   filter options : {'mode': 'aggressive'}
Use      datepattern : Default Detectors
Use         log file : /tmp/gh-2624.txt
Use         encoding : UTF-8


Results
=======

Failregex: 45 total
|-  #) [# of hits] regular expression
|   8) [45] ^from [^[]*\[<HOST>\](?::\d+)?:?
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [52] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
`-

Lines: 52 lines, 0 ignored, 45 matched, 7 missed
[processed in 0.00 sec]

|- Missed line(s):
|  Feb  6 12:57:22 l03 postfix/smtpd[24476]: disconnect from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
|  Feb  6 12:57:23 l03 postfix/smtpd[26292]: disconnect from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
|  Feb  6 12:57:23 l03 postfix/smtpd[29554]: disconnect from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
|  Feb  6 12:57:23 l03 postfix/smtpd[27914]: connect from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
|  Feb  6 12:57:23 l03 postfix/smtpd[26292]: connect from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
|  Feb  6 12:57:23 l03 postfix/smtpd[27914]: disconnect from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
|  Feb  6 12:57:24 l03 postfix/smtpd[24476]: connect from unknown[fd98:54b1:26d0:2e1d:0:dead:beef:a113]
`-
```
</details>

So just remove your customization and set mode in `postfix` jail:
```ini
[postfix]
mode = aggressive
```

That's it.

**Comment by ChristopherW** [comment]
Ah! I'll give that a try now with aggressive. Excellent that it's already in the stock filter, I just didn't realise :)

The prefregex and dynamic mode inside a filter is a new concept to me, I've mostly been using the older builds of f2b due to OS constraints (and free time) so this is a great introduction to some of the new features. Thanks again.
